actions {
	reject = 11;
	add_header = 5;
	greylist = 4;
        rewrite_subject = 5;
}

subject = "*** SPAM *** %s";

symbol "IP_SCORE" {
  weight = 2.0;
  description = "IP reputation";
}

symbol "R_SPF_FAIL" {
  weight = 2.0;
  description = "SPF verification failed";
}

group "bayes" {
	symbol "BAYES_SPAM" {
		weight = 5.0;
		description = "Message probably spam, probability: ";
	}
	symbol "BAYES_HAM" {
		weight = -2.5;
		description = "Message probably ham, probability: ";
	}
}
group "MX" {
	symbol "MX_INVALID" {
	  score = 1;
	  description = "No connectable MX";
	  one_shot = true;
	}
	symbol "MX_MISSING" {
	  score = 2.0;
	  description = "No MX record";
	  one_shot = true;
	}
	symbol "MX_GOOD" {
	  score = -0.01;
	  description = "MX was ok";
	  one_shot = true;
	}
}

group "local" {
  symbol "LOCAL_BL_IP" {
    weight = 6.0;
    description = "Sender ip listed in local ip blacklist";
  }
  symbol "LOCAL_BL_FROM" {
    weight = 6.0;
    description = "Sender from listed in local from blacklist";
  }
  symbol "LOCAL_BL_RCPT" {
    weight = 6.0;
    description = "Recipient listed in local rcpt blacklist";
  }
  symbol "LOCAL_WL_IP" {
    weight = -5.0;
    description = "Sender ip listed in local ip whitelist";
  }
  symbol "LOCAL_WL_FROM" {
    weight = -5.0;
    description = "Sender from listed in local from whitelist";
  }
  symbol "LOCAL_WL_RCPT" {
    weight = -5.0;
    description = "Recipient listed in local rcpt whitelist";
  }
}
