# Какие файлы запретить в почте.

filename_blacklist {
  type = "filename";
  filter = "extension";
  map = "/data/rspamd/filename.map";
  symbol = "FILENAME_BLACKLISTED";
  action = "reject";
}

# Черный список по домену.

local_bl_from {
  # Какие данные из письма брать для сравнения, в моем случае анализируется отправитель
  type = "from";
  # К каждому виду анализа, который задается с помощью параметра "type" возможно
  # задать дополнительные параметры. В данном случае из адреса отправителя
  # например user@example.ru для проверки будет браться только доменная часть.
  filter = "email:domain";
  # Разрешить использование регулярных выражений в файле
  regexp = true;
  # Заранее определенный "символ", в соответствии с которым будут начислены
  # спам баллы
  symbol = "LOCAL_BL_FROM";
  # Файл со списком доменов ($LOCAL_CONFDIR раскрывается как /usr/local/etc/rspamd)
  map = "/data/rspamd/blacklist.map";
  # Описание
  description = "Local blacklist rule";
}

# Белый список по домену

local_wl_from {
  # Какие данные из письма брать для сравнения, в моем случае анализируется отправитель
  type = "from";
  # К каждому виду анализа, который задается с помощью параметра "type" возможно
  # задать дополнительные параметры. В данном случае из адреса отправителя
  # например user@example.ru для проверки будет браться только доменная часть.
  filter = "email:domain";
  # Разрешить использование регулярных выражений в файле
  #regexp = true;
  # Заранее определенный "символ", в соответствии с которым будут начислены
  # спам баллы
  symbol = "LOCAL_WL_FROM";
  # Файл со списком доменов ($LOCAL_CONFDIR раскрывается как /usr/local/etc/rspamd)
  map = "/data/rspamd/whitelist.map";
  # Описание
  description = "Local whitelist rule";
}

# Добавим несколько баллов всем странам, кроме списка

COUNTRY_CHECK {

  type = "country";
  regexp = true;
  map = "/data/rspamd/country.map";
  description = "Country multimap banned";
  score = 2.0;
}

SUBJECT_CHECK {

  type = "header";
  header = "subject";
  regexp = true;
  map = "/data/rspamd/regexp.map";
  description = "subject multimap banned";
  score = 4.5;
}

SENDER_NAME {

  type = "from";
  filter = "email:name";
  regexp = true;
  map = "/data/rspamd/emailname.map";
  description = "name  multimap banned";
  score = 1.0;
}

