classifier "bayes" {
    tokenizer {
    name = "osb";
    }
  backend = "redis";
  servers = "127.0.0.1";
  min_tokens = 4;
  min_learns = 100;

  statfile {
    symbol = "BAYES_HAM";
    spam = false;
  }
  statfile {
    symbol = "BAYES_SPAM";
    spam = true;
  }
  autolearn = true
# per_user = true;
}
