[INCLUDES]

#before = paths-distro.conf
before = paths-debian.conf

# The DEFAULT allows a global definition of the options. They can be overridden
# in each jail afterwards.

[DEFAULT]
ignoreip = 127.0.0.1/8 17.0.0.1/8 192.168.0.0/16
bantime  = 30m
findtime  = 30m
maxretry = 5
backend = auto
usedns = warn
logencoding = auto
enabled = false
mode = normal


[postfix-sasl2]
enabled = true
port = smtp
filter = postfix-sasl2
action = iptables-multiport[name=Postfix-sasl, port="smtp,ssmtp,465,submission,imap,imaps,pop3,pop3s"]
logpath = /var/log/mail.log
findtime = 60m
maxretry = 4
bantime = 24h
