
server {
        listen 443 ssl;
        ssl_certificate      {{ FULLCERT }};
        ssl_certificate_key  {{ KEYFILE }};

        access_log off;
        error_log off;

        server_name autoconfig.* autodiscover.*;
        root /var/www/autoconfig;

        location = /robots.txt {
        allow all;
        log_not_found off;
        }

        location /mail {
        rewrite ^/mail/config-.*\.xml$ /autoconfig.php;
        }
        location = /autodiscover/autodiscover.xml {
        rewrite ^(.*)$ /autoconfig.php;
        }

        location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass      unix:/var/run/php82-fpm.sock;
        fastcgi_index     index.php;
        fastcgi_param HTTPS on;
        include           fastcgi.conf;
       }
}



server {
	listen 80;
	server_name autoconfig.* autodiscover.*;

	root /var/www/autoconfig;

	location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
	}

	location /mail {
	rewrite ^/mail/config-.*\.xml$ /autoconfig.php;
	}
	location = /autodiscover/autodiscover.xml {
	rewrite ^(.*)$ /autoconfig.php;
	}

        location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass      unix:/var/run/php82-fpm.sock;
        fastcgi_index     index.php;
        include           fastcgi.conf;
       }

}
