server {
    ssl_certificate      {{ FULLCERT }};
    ssl_certificate_key  {{ KEYFILE }};
    listen 9999 ssl;
    server_name	    _;
    root            /usr/share/webapps/postfixadmin/public/;
    index           index.php;
    charset         utf-8;

    error_log /dev/stdout info;
    access_log /dev/stdout;    

    add_header Strict-Transport-Security max-age=31536000;
    # add_header X-Frame-Options DENY;

    # auth_basic "Restricted area";
    # auth_basic_user_file /etc/nginx/passwd;

    location / {
        try_files $uri $uri/ index.php;
    }

            location ~ \.php$ {
              fastcgi_pass      unix:/var/run/php81-fpm.sock;
              fastcgi_index     index.php;
              include           fastcgi.conf;
        }
}
