# Фильтр Fail2Ban для ошибок аутентификации Dovecot

[INCLUDES]
before = common.conf

[Definition]
_daemon = dovecot
failregex = dovecot: (?:pop3-login|imap-login): Disconnected: .*\bauth failed\b.*rip=<HOST>
ignoreregex =
