# New filter because Postfix SASL filter does not work
#
# Fail2Ban filter for postfix authentication failures
#

[INCLUDES]
before = common.conf

[Definition]
_daemon = postfix/(submission/)?smtp(d|s)
failregex = postfix\/smtpd\[\d+\]: warning: .*\[<HOST>\]: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed
ignoreregex = authentication failed: Connection lost to authentication server$

[Init]
ignoreregex =
