/var/log/*.log /var/log/mail.log /var/log/messages /var/log/nginx/*.log /var/log/supervisor/*.log {
  rotate 7
  daily
  compress
  missingok
  notifempty
  copytruncate
  sharedscripts
  maxsize 50M
}
