[supervisord] 
nodaemon=true 

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=root:nginx

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:syslog] 
command=/usr/sbin/rsyslogd -n 
redirect_stderr=true
stdout_logfile=/var/log/supervisor/syslog.log
autorestart=true

[program:dcron]
command=/usr/sbin/crond -f -l 8 -d
directory=/
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/cron.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=3
environment=PATH="/usr/sbin:/usr/bin:/sbin:/bin"


[program:redis]
command=/usr/bin/redis-server
directory = /data/redis
redirect_stderr=true
stdout_logfile=/var/log/supervisor/redis.log
autorestart=true

[program:nginx] 
command=/usr/sbin/nginx -g 'daemon off;' 
redirect_stderr=true
stdout_logfile=/var/log/supervisor/nginx.log
autorestart=unexpected

[program:php] 
command=/usr/sbin/php-fpm82 --nodaemonize --fpm-config /etc/php82/php-fpm.conf 
redirect_stderr=true
stdout_logfile=/var/log/supervisor/php.log
autorestart=true

[program:dovecot] 
command=/usr/sbin/dovecot -F 
redirect_stderr=true
stdout_logfile=/var/log/supervisor/dovecot.log
autorestart=true

[program:mysql] 
command=/usr/bin/mysqld --user=mysql --datadir /data/mysql
username = mysql 
redirect_stderr=true
stdout_logfile=/var/log/supervisor/mysql.log
autorestart=true

[program:postfix] 
command=/scripts/postfix.sh 
redirect_stderr=true
stdout_logfile=/var/log/supervisor/postfix.log
autorestart=true

[program:rspamd]
command=/usr/bin/rspamd -u rspamd -g rspamd -p /var/run/rspamd.pid -f
autorestart=true

[program:fail2ban]
command=/usr/bin/fail2ban-server -f -x -v start
autorestart=true

